require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/*'
    - 'Gemfile'
Metrics/BlockLength:
  Exclude:
    - 'config/**/*'

Style/Documentation:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false
